FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 1433

ENV ASPNETCORE_ENVIRONMENT=Release

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Prechart.Service.Documents/Prechart.Service.Documents.Upload.csproj", "Prechart.Service.Documents/"]
COPY ["Prechart.Service.Core/Prechart.Service.Core.csproj", "Prechart.Service.Core/"]
COPY ["Prechart.Service.Globals/Prechart.Service.Globals.csproj", "Prechart.Service.Globals/"]
COPY ["Prechart.Service.AuditLog/Prechart.Service.AuditLog.csproj", "Prechart.Service.AuditLog/"]
RUN dotnet restore "Prechart.Service.Documents/Prechart.Service.Documents.Upload.csproj"
COPY . .
WORKDIR "/src/Prechart.Service.Documents"
RUN dotnet build "Prechart.Service.Documents.Upload.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Prechart.Service.Documents.Upload.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir -p /app/config

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y curl iputils-ping && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["dotnet", "Prechart.Service.Documents.Upload.dll"]
