//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Prechart.Service.Globals.Models.Loonheffings.Xsd.Xsd2022
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01", IsNullable=false)]
    public partial class Loonaangifte {
        
        private BerichtType berichtField;
        
        private LoonaangifteAdministratieveEenheid administratieveEenheidField;
        
        private LoonaangifteVersion versionField;
        
        /// <remarks/>
        public BerichtType Bericht {
            get {
                return this.berichtField;
            }
            set {
                this.berichtField = value;
            }
        }
        
        /// <remarks/>
        public LoonaangifteAdministratieveEenheid AdministratieveEenheid {
            get {
                return this.administratieveEenheidField;
            }
            set {
                this.administratieveEenheidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LoonaangifteVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class BerichtType {
        
        private string idBerField;
        
        private System.DateTime datTdAanmField;
        
        private string contPersField;
        
        private string telNrField;
        
        private string relNrField;
        
        private string gebrSwPakketField;
        
        /// <remarks/>
        public string IdBer {
            get {
                return this.idBerField;
            }
            set {
                this.idBerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatTdAanm {
            get {
                return this.datTdAanmField;
            }
            set {
                this.datTdAanmField = value;
            }
        }
        
        /// <remarks/>
        public string ContPers {
            get {
                return this.contPersField;
            }
            set {
                this.contPersField = value;
            }
        }
        
        /// <remarks/>
        public string TelNr {
            get {
                return this.telNrField;
            }
            set {
                this.telNrField = value;
            }
        }
        
        /// <remarks/>
        public string RelNr {
            get {
                return this.relNrField;
            }
            set {
                this.relNrField = value;
            }
        }
        
        /// <remarks/>
        public string GebrSwPakket {
            get {
                return this.gebrSwPakketField;
            }
            set {
                this.gebrSwPakketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class TijdvakCorrectieType {
        
        private System.DateTime datAanvTvField;
        
        private System.DateTime datEindTvField;
        
        private CollectieveAangifteType collectieveAangifteField;
        
        private InkomstenverhoudingInitieelType[] inkomstenverhoudingInitieelField;
        
        private InkomstenverhoudingIntrekkingType[] inkomstenverhoudingIntrekkingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatAanvTv {
            get {
                return this.datAanvTvField;
            }
            set {
                this.datAanvTvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatEindTv {
            get {
                return this.datEindTvField;
            }
            set {
                this.datEindTvField = value;
            }
        }
        
        /// <remarks/>
        public CollectieveAangifteType CollectieveAangifte {
            get {
                return this.collectieveAangifteField;
            }
            set {
                this.collectieveAangifteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InkomstenverhoudingInitieel")]
        public InkomstenverhoudingInitieelType[] InkomstenverhoudingInitieel {
            get {
                return this.inkomstenverhoudingInitieelField;
            }
            set {
                this.inkomstenverhoudingInitieelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InkomstenverhoudingIntrekking")]
        public InkomstenverhoudingIntrekkingType[] InkomstenverhoudingIntrekking {
            get {
                return this.inkomstenverhoudingIntrekkingField;
            }
            set {
                this.inkomstenverhoudingIntrekkingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CollectieveAangifteTijdvakAangifteType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class CollectieveAangifteType {
        
        private string totLnLbPhField;
        
        private string totLnSVField;
        
        private string totPrlnAofAnwLgField;
        
        private string totPrlnAofAnwHgField;
        
        private string totPrlnAofAnwUitField;
        
        private string totPrlnAwfAnwLgField;
        
        private string totPrlnAwfAnwHgField;
        
        private string totPrlnAwfAnwHzField;
        
        private string prLnUFOField;
        
        private string ingLbPhField;
        
        private string eHPubUitkField;
        
        private string eHGebrAutoField;
        
        private string eHVUTField;
        
        private string ehOvsFrfWrkkstrgField;
        
        private string aVZeevField;
        
        private string vrlAVSOField;
        
        private string totPrAofLgField;
        
        private string totPrAofHgField;
        
        private string totPrAofUitField;
        
        private string totOpslWkoField;
        
        private string totPrGediffWhkField;
        
        private string totPrAwfLgField;
        
        private string totPrAwfHgField;
        
        private string totPrAwfHzField;
        
        private string prUFOField;
        
        private string ingBijdrZvwField;
        
        private string totWghZvwField;
        
        private string totTeBetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotLnLbPh {
            get {
                return this.totLnLbPhField;
            }
            set {
                this.totLnLbPhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotLnSV {
            get {
                return this.totLnSVField;
            }
            set {
                this.totLnSVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrlnAofAnwLg {
            get {
                return this.totPrlnAofAnwLgField;
            }
            set {
                this.totPrlnAofAnwLgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrlnAofAnwHg {
            get {
                return this.totPrlnAofAnwHgField;
            }
            set {
                this.totPrlnAofAnwHgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrlnAofAnwUit {
            get {
                return this.totPrlnAofAnwUitField;
            }
            set {
                this.totPrlnAofAnwUitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrlnAwfAnwLg {
            get {
                return this.totPrlnAwfAnwLgField;
            }
            set {
                this.totPrlnAwfAnwLgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrlnAwfAnwHg {
            get {
                return this.totPrlnAwfAnwHgField;
            }
            set {
                this.totPrlnAwfAnwHgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrlnAwfAnwHz {
            get {
                return this.totPrlnAwfAnwHzField;
            }
            set {
                this.totPrlnAwfAnwHzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PrLnUFO {
            get {
                return this.prLnUFOField;
            }
            set {
                this.prLnUFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IngLbPh {
            get {
                return this.ingLbPhField;
            }
            set {
                this.ingLbPhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EHPubUitk {
            get {
                return this.eHPubUitkField;
            }
            set {
                this.eHPubUitkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EHGebrAuto {
            get {
                return this.eHGebrAutoField;
            }
            set {
                this.eHGebrAutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EHVUT {
            get {
                return this.eHVUTField;
            }
            set {
                this.eHVUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string EhOvsFrfWrkkstrg {
            get {
                return this.ehOvsFrfWrkkstrgField;
            }
            set {
                this.ehOvsFrfWrkkstrgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string AVZeev {
            get {
                return this.aVZeevField;
            }
            set {
                this.aVZeevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string VrlAVSO {
            get {
                return this.vrlAVSOField;
            }
            set {
                this.vrlAVSOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrAofLg {
            get {
                return this.totPrAofLgField;
            }
            set {
                this.totPrAofLgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrAofHg {
            get {
                return this.totPrAofHgField;
            }
            set {
                this.totPrAofHgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrAofUit {
            get {
                return this.totPrAofUitField;
            }
            set {
                this.totPrAofUitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotOpslWko {
            get {
                return this.totOpslWkoField;
            }
            set {
                this.totOpslWkoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrGediffWhk {
            get {
                return this.totPrGediffWhkField;
            }
            set {
                this.totPrGediffWhkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrAwfLg {
            get {
                return this.totPrAwfLgField;
            }
            set {
                this.totPrAwfLgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrAwfHg {
            get {
                return this.totPrAwfHgField;
            }
            set {
                this.totPrAwfHgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotPrAwfHz {
            get {
                return this.totPrAwfHzField;
            }
            set {
                this.totPrAwfHzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string PrUFO {
            get {
                return this.prUFOField;
            }
            set {
                this.prUFOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string IngBijdrZvw {
            get {
                return this.ingBijdrZvwField;
            }
            set {
                this.ingBijdrZvwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotWghZvw {
            get {
                return this.totWghZvwField;
            }
            set {
                this.totWghZvwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotTeBet {
            get {
                return this.totTeBetField;
            }
            set {
                this.totTeBetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class CollectieveAangifteTijdvakAangifteType : CollectieveAangifteType {
        
        private CollectieveAangifteTijdvakAangifteTypeSaldoCorrectiesVoorgaandTijdvak[] saldoCorrectiesVoorgaandTijdvakField;
        
        private string totGenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SaldoCorrectiesVoorgaandTijdvak")]
        public CollectieveAangifteTijdvakAangifteTypeSaldoCorrectiesVoorgaandTijdvak[] SaldoCorrectiesVoorgaandTijdvak {
            get {
                return this.saldoCorrectiesVoorgaandTijdvakField;
            }
            set {
                this.saldoCorrectiesVoorgaandTijdvakField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TotGen {
            get {
                return this.totGenField;
            }
            set {
                this.totGenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class CollectieveAangifteTijdvakAangifteTypeSaldoCorrectiesVoorgaandTijdvak {
        
        private System.DateTime datAanvTvField;
        
        private System.DateTime datEindTvField;
        
        private string saldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatAanvTv {
            get {
                return this.datAanvTvField;
            }
            set {
                this.datAanvTvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatEindTv {
            get {
                return this.datEindTvField;
            }
            set {
                this.datEindTvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class InkomstenverhoudingInitieelType : InkomstenverhoudingType {
        
        private InkomstenverhoudingInitieelTypeNatuurlijkPersoon natuurlijkPersoonField;
        
        private InkomstenperiodeInitieelType[] inkomstenperiodeField;
        
        private WerknemersgegevensType werknemersgegevensField;
        
        private SectorType[] sectorField;
        
        /// <remarks/>
        public InkomstenverhoudingInitieelTypeNatuurlijkPersoon NatuurlijkPersoon {
            get {
                return this.natuurlijkPersoonField;
            }
            set {
                this.natuurlijkPersoonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Inkomstenperiode")]
        public InkomstenperiodeInitieelType[] Inkomstenperiode {
            get {
                return this.inkomstenperiodeField;
            }
            set {
                this.inkomstenperiodeField = value;
            }
        }
        
        /// <remarks/>
        public WerknemersgegevensType Werknemersgegevens {
            get {
                return this.werknemersgegevensField;
            }
            set {
                this.werknemersgegevensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sector")]
        public SectorType[] Sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class InkomstenverhoudingInitieelTypeNatuurlijkPersoon : NatuurlijkPersoonType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdresBinnenland", typeof(AdresBinnenlandType))]
        [System.Xml.Serialization.XmlElementAttribute("AdresBuitenland", typeof(AdresBuitenlandType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class AdresBinnenlandType {
        
        private string strField;
        
        private string huisNrField;
        
        private string huisNrToevField;
        
        private string locOmsField;
        
        private string pcField;
        
        private string woonplField;
        
        /// <remarks/>
        public string Str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string HuisNr {
            get {
                return this.huisNrField;
            }
            set {
                this.huisNrField = value;
            }
        }
        
        /// <remarks/>
        public string HuisNrToev {
            get {
                return this.huisNrToevField;
            }
            set {
                this.huisNrToevField = value;
            }
        }
        
        /// <remarks/>
        public string LocOms {
            get {
                return this.locOmsField;
            }
            set {
                this.locOmsField = value;
            }
        }
        
        /// <remarks/>
        public string Pc {
            get {
                return this.pcField;
            }
            set {
                this.pcField = value;
            }
        }
        
        /// <remarks/>
        public string Woonpl {
            get {
                return this.woonplField;
            }
            set {
                this.woonplField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class AdresBuitenlandType {
        
        private string strField;
        
        private string huisNrField;
        
        private string locOmsField;
        
        private string pcField;
        
        private string woonplField;
        
        private string regField;
        
        private string landCdField;
        
        /// <remarks/>
        public string Str {
            get {
                return this.strField;
            }
            set {
                this.strField = value;
            }
        }
        
        /// <remarks/>
        public string HuisNr {
            get {
                return this.huisNrField;
            }
            set {
                this.huisNrField = value;
            }
        }
        
        /// <remarks/>
        public string LocOms {
            get {
                return this.locOmsField;
            }
            set {
                this.locOmsField = value;
            }
        }
        
        /// <remarks/>
        public string Pc {
            get {
                return this.pcField;
            }
            set {
                this.pcField = value;
            }
        }
        
        /// <remarks/>
        public string Woonpl {
            get {
                return this.woonplField;
            }
            set {
                this.woonplField = value;
            }
        }
        
        /// <remarks/>
        public string Reg {
            get {
                return this.regField;
            }
            set {
                this.regField = value;
            }
        }
        
        /// <remarks/>
        public string LandCd {
            get {
                return this.landCdField;
            }
            set {
                this.landCdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class NatuurlijkPersoonType {
        
        private string sofiNrField;
        
        private string voorlField;
        
        private string voorvField;
        
        private string signNmField;
        
        private System.DateTime gebdatField;
        
        private bool gebdatFieldSpecified;
        
        private string natField;
        
        private Gesl geslField;
        
        private bool geslFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string SofiNr {
            get {
                return this.sofiNrField;
            }
            set {
                this.sofiNrField = value;
            }
        }
        
        /// <remarks/>
        public string Voorl {
            get {
                return this.voorlField;
            }
            set {
                this.voorlField = value;
            }
        }
        
        /// <remarks/>
        public string Voorv {
            get {
                return this.voorvField;
            }
            set {
                this.voorvField = value;
            }
        }
        
        /// <remarks/>
        public string SignNm {
            get {
                return this.signNmField;
            }
            set {
                this.signNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Gebdat {
            get {
                return this.gebdatField;
            }
            set {
                this.gebdatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GebdatSpecified {
            get {
                return this.gebdatFieldSpecified;
            }
            set {
                this.gebdatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string Nat {
            get {
                return this.natField;
            }
            set {
                this.natField = value;
            }
        }
        
        /// <remarks/>
        public Gesl Gesl {
            get {
                return this.geslField;
            }
            set {
                this.geslField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GeslSpecified {
            get {
                return this.geslFieldSpecified;
            }
            set {
                this.geslFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum Gesl {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class InkomstenperiodeInitieelType {
        
        private System.DateTime datAanvField;
        
        private CdSrtIV srtIVField;
        
        private CdAard cdAardField;
        
        private bool cdAardFieldSpecified;
        
        private string cdInvlVplField;
        
        private FsIndFZ fsIndFZField;
        
        private bool fsIndFZFieldSpecified;
        
        private string cAOField;
        
        private string cdCaoInlField;
        
        private Indicatie indArbovOnbepTdField;
        
        private bool indArbovOnbepTdFieldSpecified;
        
        private Indicatie indSchriftArbovField;
        
        private bool indSchriftArbovFieldSpecified;
        
        private Indicatie indOprovField;
        
        private bool indOprovFieldSpecified;
        
        private IndicatieJ indJrurennrmField;
        
        private bool indJrurennrmFieldSpecified;
        
        private Indicatie indPubAanOnbepTdField;
        
        private bool indPubAanOnbepTdFieldSpecified;
        
        private Indicatie indAvrLkvOudrWnField;
        
        private bool indAvrLkvOudrWnFieldSpecified;
        
        private Indicatie indAvrLkvAgWnField;
        
        private bool indAvrLkvAgWnFieldSpecified;
        
        private Indicatie indAvrLkvDgBafSbField;
        
        private bool indAvrLkvDgBafSbFieldSpecified;
        
        private Indicatie indAvrLkvHpAgWnField;
        
        private bool indAvrLkvHpAgWnFieldSpecified;
        
        private Indicatie indLhKortField;
        
        private CdRdnGnBijt cdRdnGnBijtField;
        
        private bool cdRdnGnBijtFieldSpecified;
        
        private LbTab lbTabField;
        
        private Indicatie indWAOField;
        
        private Indicatie indWWField;
        
        private Indicatie indZWField;
        
        private Indicatie indWgldOudReglField;
        
        private bool indWgldOudReglFieldSpecified;
        
        private CdZvw cdZvwField;
        
        private Indicatie indVakBnField;
        
        private bool indVakBnFieldSpecified;
        
        private Indicatie indSA71Field;
        
        private bool indSA71FieldSpecified;
        
        private Indicatie indSA72Field;
        
        private bool indSA72FieldSpecified;
        
        private Indicatie indSA03Field;
        
        private bool indSA03FieldSpecified;
        
        private CdIncInkVerm cdIncInkVermField;
        
        private bool cdIncInkVermFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatAanv {
            get {
                return this.datAanvField;
            }
            set {
                this.datAanvField = value;
            }
        }
        
        /// <remarks/>
        public CdSrtIV SrtIV {
            get {
                return this.srtIVField;
            }
            set {
                this.srtIVField = value;
            }
        }
        
        /// <remarks/>
        public CdAard CdAard {
            get {
                return this.cdAardField;
            }
            set {
                this.cdAardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CdAardSpecified {
            get {
                return this.cdAardFieldSpecified;
            }
            set {
                this.cdAardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CdInvlVpl {
            get {
                return this.cdInvlVplField;
            }
            set {
                this.cdInvlVplField = value;
            }
        }
        
        /// <remarks/>
        public FsIndFZ FsIndFZ {
            get {
                return this.fsIndFZField;
            }
            set {
                this.fsIndFZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FsIndFZSpecified {
            get {
                return this.fsIndFZFieldSpecified;
            }
            set {
                this.fsIndFZFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string CAO {
            get {
                return this.cAOField;
            }
            set {
                this.cAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string CdCaoInl {
            get {
                return this.cdCaoInlField;
            }
            set {
                this.cdCaoInlField = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndArbovOnbepTd {
            get {
                return this.indArbovOnbepTdField;
            }
            set {
                this.indArbovOnbepTdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndArbovOnbepTdSpecified {
            get {
                return this.indArbovOnbepTdFieldSpecified;
            }
            set {
                this.indArbovOnbepTdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndSchriftArbov {
            get {
                return this.indSchriftArbovField;
            }
            set {
                this.indSchriftArbovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndSchriftArbovSpecified {
            get {
                return this.indSchriftArbovFieldSpecified;
            }
            set {
                this.indSchriftArbovFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndOprov {
            get {
                return this.indOprovField;
            }
            set {
                this.indOprovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndOprovSpecified {
            get {
                return this.indOprovFieldSpecified;
            }
            set {
                this.indOprovFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public IndicatieJ IndJrurennrm {
            get {
                return this.indJrurennrmField;
            }
            set {
                this.indJrurennrmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndJrurennrmSpecified {
            get {
                return this.indJrurennrmFieldSpecified;
            }
            set {
                this.indJrurennrmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndPubAanOnbepTd {
            get {
                return this.indPubAanOnbepTdField;
            }
            set {
                this.indPubAanOnbepTdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndPubAanOnbepTdSpecified {
            get {
                return this.indPubAanOnbepTdFieldSpecified;
            }
            set {
                this.indPubAanOnbepTdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndAvrLkvOudrWn {
            get {
                return this.indAvrLkvOudrWnField;
            }
            set {
                this.indAvrLkvOudrWnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndAvrLkvOudrWnSpecified {
            get {
                return this.indAvrLkvOudrWnFieldSpecified;
            }
            set {
                this.indAvrLkvOudrWnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndAvrLkvAgWn {
            get {
                return this.indAvrLkvAgWnField;
            }
            set {
                this.indAvrLkvAgWnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndAvrLkvAgWnSpecified {
            get {
                return this.indAvrLkvAgWnFieldSpecified;
            }
            set {
                this.indAvrLkvAgWnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndAvrLkvDgBafSb {
            get {
                return this.indAvrLkvDgBafSbField;
            }
            set {
                this.indAvrLkvDgBafSbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndAvrLkvDgBafSbSpecified {
            get {
                return this.indAvrLkvDgBafSbFieldSpecified;
            }
            set {
                this.indAvrLkvDgBafSbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndAvrLkvHpAgWn {
            get {
                return this.indAvrLkvHpAgWnField;
            }
            set {
                this.indAvrLkvHpAgWnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndAvrLkvHpAgWnSpecified {
            get {
                return this.indAvrLkvHpAgWnFieldSpecified;
            }
            set {
                this.indAvrLkvHpAgWnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndLhKort {
            get {
                return this.indLhKortField;
            }
            set {
                this.indLhKortField = value;
            }
        }
        
        /// <remarks/>
        public CdRdnGnBijt CdRdnGnBijt {
            get {
                return this.cdRdnGnBijtField;
            }
            set {
                this.cdRdnGnBijtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CdRdnGnBijtSpecified {
            get {
                return this.cdRdnGnBijtFieldSpecified;
            }
            set {
                this.cdRdnGnBijtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public LbTab LbTab {
            get {
                return this.lbTabField;
            }
            set {
                this.lbTabField = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndWAO {
            get {
                return this.indWAOField;
            }
            set {
                this.indWAOField = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndWW {
            get {
                return this.indWWField;
            }
            set {
                this.indWWField = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndZW {
            get {
                return this.indZWField;
            }
            set {
                this.indZWField = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndWgldOudRegl {
            get {
                return this.indWgldOudReglField;
            }
            set {
                this.indWgldOudReglField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndWgldOudReglSpecified {
            get {
                return this.indWgldOudReglFieldSpecified;
            }
            set {
                this.indWgldOudReglFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CdZvw CdZvw {
            get {
                return this.cdZvwField;
            }
            set {
                this.cdZvwField = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndVakBn {
            get {
                return this.indVakBnField;
            }
            set {
                this.indVakBnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndVakBnSpecified {
            get {
                return this.indVakBnFieldSpecified;
            }
            set {
                this.indVakBnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndSA71 {
            get {
                return this.indSA71Field;
            }
            set {
                this.indSA71Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndSA71Specified {
            get {
                return this.indSA71FieldSpecified;
            }
            set {
                this.indSA71FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndSA72 {
            get {
                return this.indSA72Field;
            }
            set {
                this.indSA72Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndSA72Specified {
            get {
                return this.indSA72FieldSpecified;
            }
            set {
                this.indSA72FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Indicatie IndSA03 {
            get {
                return this.indSA03Field;
            }
            set {
                this.indSA03Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndSA03Specified {
            get {
                return this.indSA03FieldSpecified;
            }
            set {
                this.indSA03FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CdIncInkVerm CdIncInkVerm {
            get {
                return this.cdIncInkVermField;
            }
            set {
                this.cdIncInkVermField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CdIncInkVermSpecified {
            get {
                return this.cdIncInkVermFieldSpecified;
            }
            set {
                this.cdIncInkVermFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum CdSrtIV {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("57")]
        Item57,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("58")]
        Item58,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("59")]
        Item59,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum CdAard {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79")]
        Item79,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("81")]
        Item81,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("82")]
        Item82,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("83")]
        Item83,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum FsIndFZ {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum Indicatie {
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum IndicatieJ {
        
        /// <remarks/>
        J,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum CdRdnGnBijt {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum LbTab {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("010")]
        Item010,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("011")]
        Item011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("013")]
        Item013,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("015")]
        Item015,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("020")]
        Item020,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("022")]
        Item022,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("023")]
        Item023,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("024")]
        Item024,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("025")]
        Item025,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("221")]
        Item221,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("224")]
        Item224,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("225")]
        Item225,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("226")]
        Item226,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("227")]
        Item227,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("228")]
        Item228,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("250")]
        Item250,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("310")]
        Item310,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("311")]
        Item311,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("312")]
        Item312,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("313")]
        Item313,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("314")]
        Item314,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("315")]
        Item315,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("320")]
        Item320,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("321")]
        Item321,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("322")]
        Item322,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("323")]
        Item323,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("324")]
        Item324,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("325")]
        Item325,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("510")]
        Item510,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("511")]
        Item511,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("512")]
        Item512,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("513")]
        Item513,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("514")]
        Item514,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("515")]
        Item515,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("520")]
        Item520,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("521")]
        Item521,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("522")]
        Item522,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("523")]
        Item523,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("524")]
        Item524,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("525")]
        Item525,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("610")]
        Item610,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("611")]
        Item611,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("612")]
        Item612,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("613")]
        Item613,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("614")]
        Item614,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("615")]
        Item615,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("620")]
        Item620,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("621")]
        Item621,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("622")]
        Item622,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("623")]
        Item623,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("624")]
        Item624,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("625")]
        Item625,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("710")]
        Item710,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("711")]
        Item711,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("712")]
        Item712,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("713")]
        Item713,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("714")]
        Item714,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("715")]
        Item715,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("720")]
        Item720,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("721")]
        Item721,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("722")]
        Item722,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("723")]
        Item723,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("724")]
        Item724,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("725")]
        Item725,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("940")]
        Item940,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("950")]
        Item950,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("999")]
        Item999,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum CdZvw {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum CdIncInkVerm {
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        Z,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class WerknemersgegevensType {
        
        private decimal lnLbPhField;
        
        private decimal lnSVField;
        
        private decimal prlnAofAnwLgField;
        
        private decimal prlnAofAnwHgField;
        
        private decimal prlnAofAnwUitField;
        
        private decimal prlnAwfAnwLgField;
        
        private decimal prlnAwfAnwHgField;
        
        private decimal prlnAwfAnwHzField;
        
        private decimal prLnUfoField;
        
        private decimal lnTabBBField;
        
        private decimal vakBslField;
        
        private decimal opgRchtVakBslField;
        
        private decimal opnAvwbField;
        
        private decimal opbAvwbField;
        
        private decimal lnInGldField;
        
        private decimal wrdLnField;
        
        private decimal lnOwrkField;
        
        private decimal verstrAanvField;
        
        private decimal ingLbPhField;
        
        private decimal prAofLgField;
        
        private decimal prAofHgField;
        
        private decimal prAofUitField;
        
        private decimal opslWkoField;
        
        private decimal prGediffWhkField;
        
        private decimal prAwfLgField;
        
        private decimal prAwfHgField;
        
        private decimal prAwfHzField;
        
        private decimal prUFOField;
        
        private decimal bijdrZvwField;
        
        private decimal wghZvwField;
        
        private decimal wrdPrGebrAutField;
        
        private decimal wrknBijdrAutField;
        
        private decimal reiskField;
        
        private decimal verrArbKrtField;
        
        private string aantVerlUField;
        
        private decimal ctrctlnField;
        
        private bool ctrctlnFieldSpecified;
        
        private decimal aantCtrcturenPWkField;
        
        private bool aantCtrcturenPWkFieldSpecified;
        
        private decimal bedrRntKstvPerslField;
        
        private decimal bedrAlInWWBField;
        
        private bool bedrAlInWWBFieldSpecified;
        
        private decimal bedrRchtAlField;
        
        private bool bedrRchtAlFieldSpecified;
        
        /// <remarks/>
        public decimal LnLbPh {
            get {
                return this.lnLbPhField;
            }
            set {
                this.lnLbPhField = value;
            }
        }
        
        /// <remarks/>
        public decimal LnSV {
            get {
                return this.lnSVField;
            }
            set {
                this.lnSVField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrlnAofAnwLg {
            get {
                return this.prlnAofAnwLgField;
            }
            set {
                this.prlnAofAnwLgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrlnAofAnwHg {
            get {
                return this.prlnAofAnwHgField;
            }
            set {
                this.prlnAofAnwHgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrlnAofAnwUit {
            get {
                return this.prlnAofAnwUitField;
            }
            set {
                this.prlnAofAnwUitField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrlnAwfAnwLg {
            get {
                return this.prlnAwfAnwLgField;
            }
            set {
                this.prlnAwfAnwLgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrlnAwfAnwHg {
            get {
                return this.prlnAwfAnwHgField;
            }
            set {
                this.prlnAwfAnwHgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrlnAwfAnwHz {
            get {
                return this.prlnAwfAnwHzField;
            }
            set {
                this.prlnAwfAnwHzField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrLnUfo {
            get {
                return this.prLnUfoField;
            }
            set {
                this.prLnUfoField = value;
            }
        }
        
        /// <remarks/>
        public decimal LnTabBB {
            get {
                return this.lnTabBBField;
            }
            set {
                this.lnTabBBField = value;
            }
        }
        
        /// <remarks/>
        public decimal VakBsl {
            get {
                return this.vakBslField;
            }
            set {
                this.vakBslField = value;
            }
        }
        
        /// <remarks/>
        public decimal OpgRchtVakBsl {
            get {
                return this.opgRchtVakBslField;
            }
            set {
                this.opgRchtVakBslField = value;
            }
        }
        
        /// <remarks/>
        public decimal OpnAvwb {
            get {
                return this.opnAvwbField;
            }
            set {
                this.opnAvwbField = value;
            }
        }
        
        /// <remarks/>
        public decimal OpbAvwb {
            get {
                return this.opbAvwbField;
            }
            set {
                this.opbAvwbField = value;
            }
        }
        
        /// <remarks/>
        public decimal LnInGld {
            get {
                return this.lnInGldField;
            }
            set {
                this.lnInGldField = value;
            }
        }
        
        /// <remarks/>
        public decimal WrdLn {
            get {
                return this.wrdLnField;
            }
            set {
                this.wrdLnField = value;
            }
        }
        
        /// <remarks/>
        public decimal LnOwrk {
            get {
                return this.lnOwrkField;
            }
            set {
                this.lnOwrkField = value;
            }
        }
        
        /// <remarks/>
        public decimal VerstrAanv {
            get {
                return this.verstrAanvField;
            }
            set {
                this.verstrAanvField = value;
            }
        }
        
        /// <remarks/>
        public decimal IngLbPh {
            get {
                return this.ingLbPhField;
            }
            set {
                this.ingLbPhField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrAofLg {
            get {
                return this.prAofLgField;
            }
            set {
                this.prAofLgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrAofHg {
            get {
                return this.prAofHgField;
            }
            set {
                this.prAofHgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrAofUit {
            get {
                return this.prAofUitField;
            }
            set {
                this.prAofUitField = value;
            }
        }
        
        /// <remarks/>
        public decimal OpslWko {
            get {
                return this.opslWkoField;
            }
            set {
                this.opslWkoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrGediffWhk {
            get {
                return this.prGediffWhkField;
            }
            set {
                this.prGediffWhkField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrAwfLg {
            get {
                return this.prAwfLgField;
            }
            set {
                this.prAwfLgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrAwfHg {
            get {
                return this.prAwfHgField;
            }
            set {
                this.prAwfHgField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrAwfHz {
            get {
                return this.prAwfHzField;
            }
            set {
                this.prAwfHzField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrUFO {
            get {
                return this.prUFOField;
            }
            set {
                this.prUFOField = value;
            }
        }
        
        /// <remarks/>
        public decimal BijdrZvw {
            get {
                return this.bijdrZvwField;
            }
            set {
                this.bijdrZvwField = value;
            }
        }
        
        /// <remarks/>
        public decimal WghZvw {
            get {
                return this.wghZvwField;
            }
            set {
                this.wghZvwField = value;
            }
        }
        
        /// <remarks/>
        public decimal WrdPrGebrAut {
            get {
                return this.wrdPrGebrAutField;
            }
            set {
                this.wrdPrGebrAutField = value;
            }
        }
        
        /// <remarks/>
        public decimal WrknBijdrAut {
            get {
                return this.wrknBijdrAutField;
            }
            set {
                this.wrknBijdrAutField = value;
            }
        }
        
        /// <remarks/>
        public decimal Reisk {
            get {
                return this.reiskField;
            }
            set {
                this.reiskField = value;
            }
        }
        
        /// <remarks/>
        public decimal VerrArbKrt {
            get {
                return this.verrArbKrtField;
            }
            set {
                this.verrArbKrtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string AantVerlU {
            get {
                return this.aantVerlUField;
            }
            set {
                this.aantVerlUField = value;
            }
        }
        
        /// <remarks/>
        public decimal Ctrctln {
            get {
                return this.ctrctlnField;
            }
            set {
                this.ctrctlnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CtrctlnSpecified {
            get {
                return this.ctrctlnFieldSpecified;
            }
            set {
                this.ctrctlnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal AantCtrcturenPWk {
            get {
                return this.aantCtrcturenPWkField;
            }
            set {
                this.aantCtrcturenPWkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AantCtrcturenPWkSpecified {
            get {
                return this.aantCtrcturenPWkFieldSpecified;
            }
            set {
                this.aantCtrcturenPWkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal BedrRntKstvPersl {
            get {
                return this.bedrRntKstvPerslField;
            }
            set {
                this.bedrRntKstvPerslField = value;
            }
        }
        
        /// <remarks/>
        public decimal BedrAlInWWB {
            get {
                return this.bedrAlInWWBField;
            }
            set {
                this.bedrAlInWWBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BedrAlInWWBSpecified {
            get {
                return this.bedrAlInWWBFieldSpecified;
            }
            set {
                this.bedrAlInWWBFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal BedrRchtAl {
            get {
                return this.bedrRchtAlField;
            }
            set {
                this.bedrRchtAlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BedrRchtAlSpecified {
            get {
                return this.bedrRchtAlFieldSpecified;
            }
            set {
                this.bedrRchtAlFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class SectorType {
        
        private System.DateTime datAanvSectField;
        
        private System.DateTime datEindSectField;
        
        private bool datEindSectFieldSpecified;
        
        private string sectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatAanvSect {
            get {
                return this.datAanvSectField;
            }
            set {
                this.datAanvSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatEindSect {
            get {
                return this.datEindSectField;
            }
            set {
                this.datEindSectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatEindSectSpecified {
            get {
                return this.datEindSectFieldSpecified;
            }
            set {
                this.datEindSectFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string Sect {
            get {
                return this.sectField;
            }
            set {
                this.sectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InkomstenverhoudingInitieelType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class InkomstenverhoudingType {
        
        private string numIVField;
        
        private System.DateTime datAanvField;
        
        private System.DateTime datEindField;
        
        private bool datEindFieldSpecified;
        
        private CdRdnEindArbov cdRdnEindArbovField;
        
        private bool cdRdnEindArbovFieldSpecified;
        
        private string persNrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string NumIV {
            get {
                return this.numIVField;
            }
            set {
                this.numIVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatAanv {
            get {
                return this.datAanvField;
            }
            set {
                this.datAanvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatEind {
            get {
                return this.datEindField;
            }
            set {
                this.datEindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatEindSpecified {
            get {
                return this.datEindFieldSpecified;
            }
            set {
                this.datEindFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CdRdnEindArbov CdRdnEindArbov {
            get {
                return this.cdRdnEindArbovField;
            }
            set {
                this.cdRdnEindArbovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CdRdnEindArbovSpecified {
            get {
                return this.cdRdnEindArbovFieldSpecified;
            }
            set {
                this.cdRdnEindArbovFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PersNr {
            get {
                return this.persNrField;
            }
            set {
                this.persNrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum CdRdnEindArbov {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class InkomstenverhoudingIntrekkingType {
        
        private string numIVField;
        
        private string sofiNrField;
        
        private string persNrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string NumIV {
            get {
                return this.numIVField;
            }
            set {
                this.numIVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string SofiNr {
            get {
                return this.sofiNrField;
            }
            set {
                this.sofiNrField = value;
            }
        }
        
        /// <remarks/>
        public string PersNr {
            get {
                return this.persNrField;
            }
            set {
                this.persNrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class TijdvakAangifteType {
        
        private System.DateTime datAanvTvField;
        
        private System.DateTime datEindTvField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatAanvTv {
            get {
                return this.datAanvTvField;
            }
            set {
                this.datAanvTvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DatEindTv {
            get {
                return this.datEindTvField;
            }
            set {
                this.datEindTvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AanvullendeAangifte", typeof(TijdvakAangifteTypeAanvullendeAangifte))]
        [System.Xml.Serialization.XmlElementAttribute("VolledigeAangifte", typeof(TijdvakAangifteTypeVolledigeAangifte))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class TijdvakAangifteTypeAanvullendeAangifte {
        
        private CollectieveAangifteTijdvakAangifteType collectieveAangifteField;
        
        private InkomstenverhoudingInitieelType[] inkomstenverhoudingInitieelField;
        
        private InkomstenverhoudingIntrekkingType[] inkomstenverhoudingIntrekkingField;
        
        /// <remarks/>
        public CollectieveAangifteTijdvakAangifteType CollectieveAangifte {
            get {
                return this.collectieveAangifteField;
            }
            set {
                this.collectieveAangifteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InkomstenverhoudingInitieel")]
        public InkomstenverhoudingInitieelType[] InkomstenverhoudingInitieel {
            get {
                return this.inkomstenverhoudingInitieelField;
            }
            set {
                this.inkomstenverhoudingInitieelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InkomstenverhoudingIntrekking")]
        public InkomstenverhoudingIntrekkingType[] InkomstenverhoudingIntrekking {
            get {
                return this.inkomstenverhoudingIntrekkingField;
            }
            set {
                this.inkomstenverhoudingIntrekkingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class TijdvakAangifteTypeVolledigeAangifte {
        
        private CollectieveAangifteTijdvakAangifteType collectieveAangifteField;
        
        private InkomstenverhoudingInitieelType[] inkomstenverhoudingInitieelField;
        
        /// <remarks/>
        public CollectieveAangifteTijdvakAangifteType CollectieveAangifte {
            get {
                return this.collectieveAangifteField;
            }
            set {
                this.collectieveAangifteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InkomstenverhoudingInitieel")]
        public InkomstenverhoudingInitieelType[] InkomstenverhoudingInitieel {
            get {
                return this.inkomstenverhoudingInitieelField;
            }
            set {
                this.inkomstenverhoudingInitieelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public partial class LoonaangifteAdministratieveEenheid {
        
        private string lhNrField;
        
        private string nmIPField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public string LhNr {
            get {
                return this.lhNrField;
            }
            set {
                this.lhNrField = value;
            }
        }
        
        /// <remarks/>
        public string NmIP {
            get {
                return this.nmIPField;
            }
            set {
                this.nmIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TijdvakAangifte", typeof(TijdvakAangifteType))]
        [System.Xml.Serialization.XmlElementAttribute("TijdvakCorrectie", typeof(TijdvakCorrectieType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.belastingdienst.nl/schemas/Loonaangifte/2022/01")]
    public enum LoonaangifteVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2.0")]
        Item20,
    }
}
