// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prechart.Service.Werkgever.Database.Context;

#nullable disable

namespace Prechart.Service.Werkgever.Migrations
{
    [DbContext(typeof(WerkgeverDbContext))]
    [Migration("20220803060618_WerkgeverWhkPremiesTotaalAdd")]
    partial class WerkgeverWhkPremiesTotaalAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Prechart.Service.Werkgever.Database.Models.Werkgever", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumActiefTot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumActiefVanaf")
                        .HasColumnType("datetime2");

                    b.Property<string>("FiscaalNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("LoonheffingenExtentie")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OmzetbelastingExtentie")
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Naam");

                    b.ToTable("Werkgever");
                });

            modelBuilder.Entity("Prechart.Service.Werkgever.Database.Models.WerkgeverWhkPremies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ActiefTot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ActiefVanaf")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FlexWerkgever")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FlexWerknemer")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Totaal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,4)")
                        .HasComputedColumnSql("[FlexWerkgever] + [FlexWerknemer] + [WgaVastWerkgever] + [WgaVastWerknemer] + [ZwFlex]");

                    b.Property<int>("WerkgeverId")
                        .HasColumnType("int");

                    b.Property<decimal>("WgaVastWerkgever")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WgaVastWerknemer")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ZwFlex")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Id", "WerkgeverId");

                    b.ToTable("WerkgeverWhkPremies");
                });
#pragma warning restore 612, 618
        }
    }
}
